version: "3.3"
services:
  mongo:
    image: "mongo"
    volumes:
      - "/home/ubuntu/efs/db:/data/db"
    ports:
      - "127.0.0.1:27017:27017"
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"
    labels:
      NAME: "rabbitmq1"
  graph:
    build: "./graph-layer"
    ports:
      - "8080:4000"
    volumes:
      - "/home/ubuntu/efs:/data/cae"
      - "/home/ubuntu/efs/ipfs:/root/.jsipfs"
    environment:
      MONGO_URL: "mongodb://mongo"
      MONGO_DB: "workhub"
      MQ_URL: 'amqp://rabbitmq:rabbitmq@rabbit1'
    depends_on:
      - mongo
      - rabbit1
  stp2glb:
    image: balbatross/cae-stp2glb
    depends_on:
      - rabbit1
      - mongo
    volumes:
      - "/home/ubuntu/efs:/data/cae"
  glb2glb:
    image: balbatross/cae-glb2glb
    depends_on:
      - rabbit1
      - mongo
    volumes:
      - "/home/ubuntu/efs:/data/cae"
  gltfpack:
    image: balbatross/cae-gltfpack
    depends_on:
      - rabbit1
      - mongo
    volumes:
      - "/home/ubuntu/efs:/data/cae"
