version: "3.3"
services:
  certbot:
    image: certbot/certbot
    volumes:
      - "${WORKHUB_FS}/certbot/conf:/etc/letsencrypt"
      - "${WORKHUB_FS}/certbot/www:/var/www/certbot"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  queendb:
    image: "balbatross/queendb"
    volumes:
      - "${WORKHUB_FS}/db:/data/db"
      - "${WORKHUB_FS}/queendb:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: "defaultpassword" 
  rabbit1:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - "${WORKHUB_FS}/rabbitmq:/var/lib/rabbitmq"
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"
    labels:
      NAME: "rabbitmq"
  nginx:
    image: nginx
    volumes:
      - "${WORKHUB_FS}/certbot/conf:/etc/letsencrypt"
      - "${WORKHUB_FS}/certbot/conf/live/${WORKHUB_DOMAIN}/fullchain.pem:/etc/letsencrypt-live/fullchain.pem"
      - "${WORKHUB_FS}/certbot/conf/live/${WORKHUB_DOMAIN}/privkey.pem:/etc/letsencrypt-live/privkey.pem"
      - "${WORKHUB_FS}/certbot/www:/var/www/certbot"
      - "${WORKHUB_FS}/web-ui:/data/web-ui/"
      - "./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    expose:
      - "80"
      - "443"
    ports: 
      - "80:80"
      - "443:443"
    depends_on:
      - signal
      - graph
      - yjs
  signal:
    build: "./signal-server"
    environment:
      - VIRTUAL_PORT=6969
    expose:
      - "6969"
  yjs:
    build: "./y-websockets-server"
    volumes:
      - "${WORKHUB_FS}/yjs:/data/ydir"
    expose: 
      - "1234"
  graph:
    build:
      context: ./graph-layer
      dockerfile: "Dockerfile"
      args:
        - domain=$WORKHUB_DOMAIN
        - WEBUI_VERSION=$WEBUI_VERSION
    expose:
      - "4002"
    ports:
      - "1234:1234"
      - "4001:4001"
      - "4003:4003"
    volumes:
      - "${WORKHUB_FS}/workhub:/data/workhub"
      - "${WORKHUB_FS}:/data/cae"
      - "${WORKHUB_FS}/ipfs:/graph/workhub"
    environment:
      WORKHUB_DOMAIN: "${WORKHUB_DOMAIN}"
      O365_USER: "${O365_USER}"
      O365_PASS: "${O365_PASS}"
      RECAPTCHA_SECRET: "${RECAPTCHA_SECRET}"
      SMTP_SERVER: "${SMTP_SERVER}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASS: "${SMTP_PASS}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_NAME: "${SMTP_NAME}"
      SMTP_FROM: "${SMTP_FROM}"
      SMTP_CONTACT: "${SMTP_CONTACT}"
      QUEENDB_HOST: "queendb"
      QUEENDB_PASS: "defaultpassword"
      MQ_URL: 'amqp://rabbitmq:rabbitmq@rabbit1'
    depends_on:
      - signal
      - rabbit1
