version: "3.3"
services:
  mongo:
    image: "mongo"
    volumes:
      - "${WORKHUB_FS}/db:/data/db"
    ports:
      - "127.0.0.1:27017:27017"
  rabbit1:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - "${WORKHUB_FS}/rabbitmq:/var/lib/rabbitmq"
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"
    labels:
      NAME: "rabbitmq"
  load-balancer:
    image: nginx
    volumes:
      - "${WORKHUB_FS}/greenlock.d/${WORKHUB_DOMAIN}/cert.pem:/etc/nginx/cert.pem"
      - "${WORKHUB_FS}/greenlock.d/${WORKHUB_DOMAIN}/privkey.pem:/etc/nginx/privkey.pem"
      - "${WORKHUB_FS}/greenlock.d/${WORKHUB_DOMAIN}/fullchain.pem:/etc/nginx/fullchain.pem"
      - "./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro"
    command: [nginx-debug, '-g', 'daemon off;']
    expose:
      - "80"
    ports: 
      - "6969:80"
    depends_on:
      - signal
  signal:
    build: "./signal-server"
    expose:
      - "6969"
  graph:
    build:
      context: ./graph-layer
      dockerfile: "Dockerfile"
      args:
        - domain=$WORKHUB_DOMAIN
    ports:
      - "80:80"
      - "443:443"
      - "1234:1234"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"
    volumes:
      - "${WORKHUB_FS}/yjs:/data/yLevel"
      - "${WORKHUB_FS}:/data/cae"
      - "${WORKHUB_FS}/ipfs:/graph/workhub-graph/workhub"
      - "${WORKHUB_FS}/greenlock.d:/graph/workhub-graph/greenlock.d"
    environment:
      WORKHUB_DOMAIN: "${WORKHUB_DOMAIN}"
      MONGO_URL: "mongodb://mongo"
      MONGO_DB: "workhub"
      MQ_URL: 'amqp://rabbitmq:rabbitmq@rabbit1'
    depends_on:
      - signal
      - mongo
      - rabbit1
