version: "3.3"
services:
  mongo:
    image: "mongo"
    volumes:
      - "${WORKHUB_FS}/db:/data/db"
    ports:
      - "127.0.0.1:27017:27017"
  rabbit1:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - "${WORKHUB_FS}/rabbitmq:/var/lib/rabbitmq"
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"
    labels:
      NAME: "rabbitmq1"
  graph:
    build:
      context: .
      dockerfile: "./graph-layer/Dockerfile"
      args:
        - domain=$WORKHUB_FS
    ports:
      - "80:80"
      - "443:443"
      - "1234:1234"
    volumes:
      - "${WORKHUB_FS}/yjs:/data/yLevel"
      - "${WORKHUB_FS}:/data/cae"
      - "${WORKHUB_FS}/ipfs:/root/.jsipfs"
      - "${WORKHUB_FS}/greenlock.d:/graph/workhub-graph/greenlock.d"
    environment:
      WORKHUB_DOMAIN: "${WORKHUB_DOMAIN}"
      MONGO_URL: "mongodb://mongo"
      MONGO_DB: "workhub"
      MQ_URL: 'amqp://rabbitmq:rabbitmq@rabbit1'
    depends_on:
      - mongo
      - rabbit1 
  stp2glb:
    image: balbatross/cae-stp2glb
    depends_on:
      - rabbit1
      - mongo
    volumes:
      - "${WORKHUB_FS}:/data/cae"
  glb2glb:
    image: balbatross/cae-glb2glb
    depends_on:
      - rabbit1
      - mongo
    volumes:
      - "${WORKHUB_FS}:/data/cae"
  gltfpack:
    image: balbatross/cae-gltfpack
    depends_on:
      - rabbit1
      - mongo
    volumes:
      - "${WORKHUB_FS}:/data/cae"
